CREATE TABLE `tb_materials` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
        `CODE` VARCHAR(40) NOT NULL COMMENT '材料唯一码',
	`NAME` VARCHAR(100) NOT NULL COMMENT '材料名称',
        `PRICE` INT(11) NOT NULL COMMENT '材料单价',
	`STORAGE` INT(11) NOT NULL COMMENT '材料存库数量',
        `DESCRIPTION` TEXT COMMENT '材料描述',
	PRIMARY KEY (`ID`),
        UNIQUE INDEX `MCODE` (`CODE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;



CREATE TABLE `tb_products` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(100) NOT NULL COMMENT '产品名称',
        `PRICE` INT(11) NOT NULL COMMENT '产品价格',
        `STORAGE` INT(11) NOT NULL COMMENT '产品存库数量',
        `DESCRIPTION` TEXT COMMENT '产品描述',
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;